# Schema for the configuration files of the Freak Quizzes module.
freak_quizzes.settings:
  type: config_object
  label: 'Freak Quizzes settings'
  mapping:
    example:
      type: string
      label: 'Example'
